name: Bump version on merge

on:
  pull_request:
    branches:
      - next
    types: [closed]

jobs:
  # If pull request was merged then we should check for a package version update
  check-version-changing:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      # Checkout to target branch
      - uses: actions/checkout@v2
        with:
          # Pull submodules
          submodules: 'recursive'

      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v1
        with:
          diff-search: true

      - name: Throw an error and stop workflow if version was changed
        uses: actions/github-script@v3
        if: steps.check.outputs.changed == 'true'
        with:
          script: |
            core.setFailed('Version was changed. Do nothing.')

  bump-version:
    needs: check-version-changing
    runs-on: ubuntu-latest
    steps:
      # Checkout to target branch
      - uses: actions/checkout@v2

      # Setup node environment
      - uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: https://registry.npmjs.org/

      # Bump version to the next prerelease (patch) with rc suffix
      - name: Suggest the new version
        run: yarn version --prerelease --preid rc --no-git-tag-version

      # Get package new version name
      - name: Get package info
        id: package
        uses: codex-team/action-nodejs-package-info@v1

      # Create pull request with changes
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Bump version
          committer: GitHub <noreply@github.com>
          branch: auto-bump-version
          delete-branch: true
          title: "Bump version up to ${{ steps.package.outputs.version }}"
          body: |
            Auto-generated bump version suggestion because of PR:
            **${{ github.event.pull_request.title }}** #${{ github.event.pull_request.number }}
