name: Check for a version changing

on: push

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get package info
        id: package
        uses: codex-team/action-nodejs-package-info@v1

      - if: contains(steps.package.outputs.version, '-rc')
        run: echo 'RELEASE CANDIDATE!'




      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v1
        with:
          diff-search: true

      - uses: actions/github-script@v3
        if: steps.check.outputs.changed != 'true'
        with:
          script: |
            core.setFailed('No version changes')

      - name: Log when changed
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found in commit ${{ steps.check.outputs.commit }}! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

      - name: Log when unchanged
        if: steps.check.outputs.changed == 'false'
        run: 'echo "No version change :/"'
