name: Tests

on: [pull_request]

jobs:
  cypress:
    strategy:
      matrix:
        browser: [ firefox, chrome, edge ]

    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node14.16.0-chrome89-ff86
      options: --user 1001

    steps:
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Pull Editor.js Tools
        run: yarn pull_tools

      - name: Run cypress
        uses: cypress-io/github-action@v2
        with:
          browser: ${{ matrix.browser }}
          build: yarn build
